spring.application.name=beekeeper

spring.datasource.url=jdbc:mysql://localhost:3306/beekeeper
spring.datasource.username= root
spring.datasource.password= 2002

spring.datasource.drive-class-name=com.mysql.cj.jdbc.driver
server.error.include-message=always
server.error.include-stacktrace=always
#spring.jpa.hibernate.ddl-auto=validate

logging.file.name=mylog
logging.level.root=ERROR
